In [1]:
import numpy as np

In [2]:
print(np.__version__)
np.show_config()

1.20.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']


In [3]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
x = np.zeros((10,10))
print("%d bytes" % (x.size * x.itemsize))

800 bytes


In [5]:
#problem5

In [6]:
x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
x = np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
x = np.arange(10)
y = np.zeros(10)
for i in range(9):y[i] = x[9 - i]
print(y)

[9. 8. 7. 6. 5. 4. 3. 2. 1. 0.]


In [9]:
x = np.arange(9).reshape(3, 3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
x = np.nonzero([1,2,0,0,4,0])
print(x)

(array([0, 1, 4], dtype=int64),)


In [11]:
j=3
x = np.zeros(9).reshape(j, j)
for i in range(j):x[i][i] = 1
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
x = np.random.random((3,3,3))
print(x)

[[[0.17164532 0.17368463 0.8416334 ]
  [0.4973638  0.07390661 0.04123597]
  [0.97534966 0.22563725 0.01887156]]

 [[0.9680546  0.10452085 0.63969771]
  [0.74213749 0.59436005 0.97106809]
  [0.56140631 0.3147702  0.038598  ]]

 [[0.29423753 0.45354272 0.31543614]
  [0.83920279 0.43039029 0.3131814 ]
  [0.11948669 0.04714278 0.2934583 ]]]


In [13]:
x = np.random.random((10,10))
print(x)
xmin, xmax = x.min(), x.max()
print(xmin, xmax)

[[0.30883147 0.00257653 0.54687933 0.52145015 0.64356238 0.14295264
  0.78480981 0.31478746 0.85003945 0.22773541]
 [0.9091047  0.30086546 0.5935724  0.91776413 0.85232407 0.95446918
  0.81220031 0.8011543  0.54308183 0.60033648]
 [0.38394111 0.34504367 0.25836127 0.62273251 0.45117797 0.87379502
  0.95183579 0.71274042 0.35748141 0.35037626]
 [0.82192709 0.55307121 0.45870133 0.26093592 0.88631766 0.95533046
  0.17996739 0.27372855 0.03489172 0.62092507]
 [0.98162917 0.38996499 0.8877583  0.65542721 0.95945615 0.03564623
  0.5494938  0.03852493 0.49968255 0.3435088 ]
 [0.26227577 0.7810331  0.42138215 0.78209099 0.84773129 0.35957027
  0.10279121 0.39406861 0.96379795 0.38555239]
 [0.58829924 0.35579254 0.23281084 0.80072687 0.71939795 0.73280046
  0.11078157 0.25929883 0.49738708 0.22526508]
 [0.16474521 0.97488422 0.84954066 0.39949701 0.89505607 0.81149352
  0.67611939 0.77265116 0.16009082 0.73606041]
 [0.10285333 0.97705558 0.97066796 0.19555902 0.42664462 0.39815963
  0.67140821

In [14]:
x = np.random.random(30)
print(x)
m = x.mean()
print(m)

[0.48314139 0.45427831 0.62336116 0.55872311 0.05400922 0.1314654
 0.00114994 0.57116093 0.22830244 0.66010655 0.15850917 0.7953003
 0.98305388 0.26226321 0.84187015 0.65210177 0.18638898 0.31967253
 0.09652285 0.8045921  0.67406591 0.91763615 0.83263273 0.2721798
 0.5855923  0.45498996 0.16669369 0.57944497 0.69065479 0.74344289]
0.49277688656393676


In [15]:
x = np.ones((5,6))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [16]:
x = np.ones((5,5))
x[:, [0, -1]] = 0
x[[0, -1], :] = 0
print(x)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [18]:
x = np.diag(1+np.arange(4),k=-1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [19]:
x = np.zeros((8,8))
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [20]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [21]:
x = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [22]:
x = np.random.random((5,5))
x = (x - np.mean (x)) / (np.std (x))
print(x)

[[-0.11867365  1.44341068  0.6991076  -1.35223498  1.08804037]
 [-1.75527441  0.08017447  1.17639933  1.03454085 -0.03160144]
 [-0.96421821  1.32964106 -1.33315914  0.91901021 -1.33932721]
 [ 0.73631624 -1.14889055 -0.28878289  0.90187091  0.38662186]
 [-1.43173835  0.01369495  1.07595588 -0.58404621 -0.53683739]]


In [23]:
color = np.dtype([("r", np.ubyte),("g", np.ubyte),("b", np.ubyte),("a", np.ubyte)])

In [24]:
x = np.dot(np.ones((5,3)), np.ones((3,2)))
print(x)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [25]:
x = np.arange(10)
for i in range(6):x[i+2] *= -1
print(x)

[ 0  1 -2 -3 -4 -5 -6 -7  8  9]


In [26]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1)) 

9
10


In [27]:
#answer27

In [28]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))
#error

nan
0
[-2.14748365e+09]


<ipython-input-28-026bd3ca7060>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-28-026bd3ca7060>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


In [29]:
x = np.random.uniform(-10,+10,5)
print(np.copysign(np.ceil(np.abs(x)), x))

[  9.  -4.   9. -10. -10.]


In [30]:
x = np.random.randint(0,10,10)
y = np.random.randint(0,10,10)
print(x)
print(y)
print(np.intersect1d(x,y))

[9 1 9 8 9 7 9 1 2 5]
[6 5 2 3 9 8 7 7 0 4]
[2 5 7 8 9]


In [31]:
defaults = np.seterr(all="ignore")

In [32]:
print(np.sqrt(-1))
print(np.emath.sqrt(-1))
np.sqrt(-1) == np.emath.sqrt(-1)

nan
1j


False

In [33]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)  
print(yesterday, today, tomorrow)

2021-09-09 2021-09-10 2021-09-11


In [34]:
x = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [35]:
A = 5
B = 7
B = B*(-A/2)
A = A*(-A/2)
A = A+B
print(A)

-30.0


In [36]:
x = np.random.uniform(0,10,5)

print(x - x%1)
print(x // 1)
print(np.floor(x))
print(x.astype(int))
print(np.trunc(x))

[7. 4. 9. 2. 1.]
[7. 4. 9. 2. 1.]
[7. 4. 9. 2. 1.]
[7 4 9 2 1]
[7. 4. 9. 2. 1.]


In [37]:
x = np.tile(np.arange(0, 5), (5,1))
print(x)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [38]:
def generate():
    for i in range(10):
        yield i
x = np.fromiter(generate(),dtype=float,count=-1)
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [39]:
x = np.linspace(0,1,11,endpoint=False)[1:]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [40]:
x = np.random.random(10)
x.sort()
print(x)

[0.02140373 0.21574123 0.25517674 0.35904486 0.45827353 0.73190279
 0.78761657 0.78922543 0.87718427 0.90424648]


In [41]:
x = np.arange(5)
np.add.reduce(x)

10

In [42]:
x = np.random.random(10)
y = np.random.random(10)
print(x)
print(y)
x==y

[0.21634324 0.62061799 0.68145191 0.93069296 0.94875118 0.78020791
 0.84812598 0.49023316 0.56326213 0.87144492]
[0.07625066 0.33190405 0.45731402 0.37108239 0.9553776  0.88652948
 0.02480222 0.6210187  0.18342789 0.16493344]


array([False, False, False, False, False, False, False, False, False,
       False])

In [43]:
x = np.zeros(10)
x.flags.writeable = False

In [44]:
x = np.random.random(10)
y = np.random.random(10)
print(x)
print(y)
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(r)
print(t)

[0.86490688 0.25757401 0.36474538 0.83815787 0.6340335  0.50769608
 0.58723013 0.64093616 0.43221011 0.89173473]
[0.4920871  0.97212684 0.54389157 0.9175851  0.43550789 0.36893915
 0.88842008 0.21724823 0.55180027 0.27956438]
[0.99509478 1.0056714  0.65487192 1.24276749 0.76919802 0.62759175
 1.06495514 0.67675398 0.70092019 0.9345304 ]
[0.5172742  1.31178866 0.98006076 0.83060587 0.60186939 0.62841696
 0.98673924 0.3268011  0.90633848 0.3038013 ]


In [45]:
x = np.random.random(10)
print(x)
x[x.argmax()] = 0
print(x)

[0.61302335 0.08038989 0.10887811 0.9673834  0.68396589 0.36843306
 0.98913041 0.4955656  0.71593268 0.26020581]
[0.61302335 0.08038989 0.10887811 0.9673834  0.68396589 0.36843306
 0.         0.4955656  0.71593268 0.26020581]


In [46]:
z = np.zeros((5,5), [('x',float),('y',float)])
z['x'], z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [47]:
x = np.random.random(10)
y = np.random.random(10)
C = 1.0 / np.subtract.outer(x, y)
print(C)

[[ 179.51404306  -17.48064246  -20.47775047   -4.54839201   -7.50192771
    -2.55200004   -1.43243384   -2.38412153 -255.92555528   -1.42796342]
 [   2.24943788    2.61931793    2.56310739    4.56356369    3.2713324
    21.21548108   -3.85910253   51.16867125    2.29844094   -3.82682635]
 [  97.25248931  -19.04971738  -22.66465103   -4.64800647   -7.77682664
    -2.58306088   -1.44216777   -2.41120853 1242.95855925   -1.43763648]
 [   9.74764421   25.11795407   20.75342991   -8.14069576  -27.56280584
    -3.39177097   -1.66363269   -3.10151176   10.73988013   -1.65760576]
 [   1.31984472    1.43908051    1.42194759    1.87886445    1.61604351
     2.77589041   18.52477182    3.00613927    1.33656442   19.30642084]
 [   1.81127181    2.04364606    2.00926606    3.06119569    2.41996811
     6.46503786   -6.59696481    7.8686903     1.8429094    -6.50320244]
 [   6.13623784    9.98107852    9.21130758  -16.00968024   41.49956658
    -4.26523238   -1.84939691   -3.81612393    6.51515361  

In [48]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [49]:
np.set_printoptions(threshold=float("inf"))
x = np.ones((10,10))
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [50]:
x = np.arange(10)
y = np.random.uniform(0,10)
print(x)
print(y)
index = (np.abs(x-y)).argmin()
print(x[index])

[0 1 2 3 4 5 6 7 8 9]
4.987430101596052
5


In [51]:
#problem51

In [52]:
import scipy.spatial

x = np.random.random((100,2))
d = scipy.spatial.distance.cdist(x,x)
print(d)

[[0.         0.55509264 0.3062801  0.35301349 0.6248575  0.45274657
  0.11051346 0.44122992 0.43846288 0.39162908 0.22323684 0.24231893
  0.37620722 0.38337166 0.04294782 0.6762481  0.48939409 0.52465525
  0.43239732 0.53718851 0.37024488 0.3516837  0.65908645 0.50307823
  0.49936156 0.46138352 0.61495402 0.73729756 0.67275578 0.27679074
  0.65857996 0.38427578 0.18774419 0.36521863 0.55977799 0.55870133
  0.21848467 0.52748018 0.5034979  0.72643135 0.17444869 0.17475777
  0.58913911 0.12194279 0.74425993 0.74334206 0.64414247 0.74317321
  0.77603792 0.22645207 0.75265643 0.71946746 0.59394191 0.84986137
  0.66605996 0.57705785 0.2990208  0.43102125 0.35057291 0.12130886
  0.44399753 0.4947025  0.79012502 0.86713091 0.10958017 0.25623271
  0.51112214 0.20147782 0.5527131  0.1571946  0.19947745 0.68584957
  0.65546219 0.50726518 0.21369261 0.41717625 0.14234659 0.55093502
  0.82333634 0.68011363 0.62156734 0.76257283 0.02459444 0.21633469
  0.53100916 0.94060156 0.39618063 0.36612997 0.

In [53]:
x = (np.random.rand(10)*100).astype(np.float32)
print(x)
Y = x.view(np.int32)
Y[:] = x
print(Y)

[32.29593  98.331635 73.0369   92.24767  97.09855  45.329845 57.92579
 46.72927  85.23276  41.481792]
[32 98 73 92 97 45 57 46 85 41]


In [54]:
#question53

In [55]:
x = np.arange(4).reshape(2,2)
for index, value in np.ndenumerate(x):
    print(index, value)
for index in np.ndindex(x.shape):
    print(index, x[index])

(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3
(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3


In [56]:
x, y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
d = np.sqrt(x*x+y*y)
sigma, mu = 1.0, 0.0
g = np.exp(-( (d-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(g)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [57]:
x = np.zeros((3,3))
np.put(x, np.random.choice(range(3*3), 2, replace=False),1)
print(x)

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 0.]]


In [58]:
x = np.random.rand(5, 5)
print(x)
y = x - x.mean(axis=1, keepdims=True)
print(y)

[[0.98754849 0.85372504 0.22557938 0.45819011 0.70121861]
 [0.0399791  0.56869753 0.84838249 0.36414947 0.01885342]
 [0.48487644 0.4603258  0.42864149 0.03796736 0.07910612]
 [0.30319882 0.86898056 0.4937956  0.32646597 0.31445355]
 [0.21408115 0.78980373 0.25409314 0.40706107 0.56723695]]
[[ 0.34229616  0.20847271 -0.41967294 -0.18706222  0.05596629]
 [-0.3280333   0.20068513  0.48037009 -0.00386293 -0.34915898]
 [ 0.186693    0.16214235  0.13045804 -0.26021608 -0.21907732]
 [-0.15818008  0.40760165  0.0324167  -0.13491293 -0.14692535]
 [-0.23237406  0.34334852 -0.19236207 -0.03939414  0.12078174]]


In [59]:
x = np.random.rand(5, 5)
print(x)
i=2
print(x[x[:,i].argsort()])

[[0.31805336 0.44568388 0.04550743 0.16291094 0.1339669 ]
 [0.45580614 0.58646099 0.01999767 0.18154922 0.08199728]
 [0.08719541 0.85623875 0.26939576 0.11061295 0.52439182]
 [0.42496856 0.98016691 0.88701689 0.89692992 0.44037337]
 [0.2226398  0.51784258 0.15631556 0.5271237  0.81972919]]
[[0.45580614 0.58646099 0.01999767 0.18154922 0.08199728]
 [0.31805336 0.44568388 0.04550743 0.16291094 0.1339669 ]
 [0.2226398  0.51784258 0.15631556 0.5271237  0.81972919]
 [0.08719541 0.85623875 0.26939576 0.11061295 0.52439182]
 [0.42496856 0.98016691 0.88701689 0.89692992 0.44037337]]


In [60]:
x = np.random.rand(5, 5)
print(x)
print((~x.any(axis=0)).any())

[[0.8553273  0.51190244 0.3161621  0.21500746 0.79064563]
 [0.7500573  0.40600142 0.55240807 0.36438156 0.26275083]
 [0.82075156 0.243006   0.85516183 0.90190498 0.6677069 ]
 [0.88672264 0.19767211 0.45958935 0.00514854 0.18886781]
 [0.61272798 0.31286204 0.9032552  0.78824642 0.88045149]]
False


In [61]:
x = np.random.uniform(0,1,10)
print(x)
y = 0.5
m = x.flat[np.abs(x - y).argmin()]
print(m)

[0.02738679 0.25104468 0.1525389  0.29818746 0.73963568 0.55754236
 0.35066119 0.83634782 0.18373666 0.16566799]
0.5575423568773813


In [62]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [63]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

x = NamedArray(np.arange(10), "toolongassignment")
print (x.name)

toolongassignment


In [64]:
x = np.ones(10)
y = np.random.randint(0,len(x),20)
np.add.at(x, y, 1)
print(x)

[1. 2. 4. 3. 6. 2. 1. 3. 7. 1.]


In [65]:
x = np.random.randint(0,10,20)
y = np.random.randint(0,10,20)
print(x)
print(y)
z = np.bincount(x,y)
print(z)

[4 5 7 6 5 5 2 2 1 0 5 0 5 0 4 6 2 9 0 5]
[8 7 4 0 8 5 2 1 8 6 3 8 9 7 3 3 4 3 1 8]
[22.  8.  7.  0. 11. 40.  3.  4.  0.  3.]


In [66]:
w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)

I24 = np.dot(I.astype(np.uint32),[1,256,65536])

n = len(np.unique(I24))
print(n)

64


In [67]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[43 47 49 57]
 [56 51 55 44]
 [52 43 60 62]]
[[43 47 49 57]
 [56 51 55 44]
 [52 43 60 62]]


In [68]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
print(D)
print(S)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)


[4.16898237e-01 7.47485982e-01 3.89755220e-01 8.39789430e-01
 5.65753157e-01 9.01973129e-01 8.13039775e-01 5.55615036e-02
 1.72993331e-01 9.17678807e-01 4.55634441e-01 1.40872230e-01
 4.19674414e-01 1.34206457e-01 2.78704476e-02 1.36328998e-01
 6.15416287e-01 8.44896929e-01 2.31073902e-01 8.16930892e-01
 2.53657260e-01 5.31079515e-01 1.64790428e-01 4.51043866e-03
 4.49805847e-01 3.54963050e-01 9.41926732e-01 8.07485664e-01
 8.26482093e-01 4.69682208e-01 6.94579032e-01 9.87810071e-01
 9.34800015e-01 2.57611310e-02 3.70110024e-01 8.21250796e-01
 6.59248394e-01 3.47478193e-01 2.03030617e-01 1.12870801e-01
 6.04428798e-01 4.52663167e-02 7.70567220e-01 1.11153902e-02
 6.45837853e-02 5.70937793e-01 6.30589064e-01 7.61677218e-01
 4.76250847e-01 6.18682756e-01 1.18117440e-01 3.46422429e-01
 4.60863079e-01 6.95147916e-03 9.97387748e-03 4.87134408e-02
 9.51780192e-03 5.83556762e-01 5.65718539e-01 2.74746230e-01
 7.84327700e-01 2.56547040e-01 1.61177972e-01 3.05767178e-01
 4.90732189e-02 8.712630

In [69]:
x = np.random.uniform(0,1,(5,5))
y = np.random.uniform(0,1,(5,5))
print(x)
print(y)
print(np.sum(x * y.T, axis=1))

[[0.19918829 0.02581794 0.57785578 0.71896958 0.34627932]
 [0.75753199 0.33832509 0.79515497 0.66199144 0.74274505]
 [0.87378168 0.94313037 0.2170812  0.25827401 0.6245505 ]
 [0.5562525  0.72632396 0.24781831 0.32714439 0.08282574]
 [0.16569507 0.57099334 0.3143227  0.86242569 0.30787329]]
[[0.48426308 0.60943329 0.38612242 0.83388696 0.82233087]
 [0.80678659 0.99103989 0.09949924 0.23069815 0.6755823 ]
 [0.17836067 0.15700827 0.49322132 0.4948755  0.27005773]
 [0.6294203  0.57793883 0.9963755  0.92035565 0.17412376]
 [0.23529998 0.58077356 0.68426048 0.21903456 0.91615104]]
[0.75436941 1.73576203 1.22298964 1.0732834  1.03912168]


In [70]:
x = np.arange(5)
y = 3
z = np.zeros(len(x) + (len(x)-1)*(y))
z[::y+1] = x
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4.]


In [71]:
x = np.ones((5,5,3))
y = 2*np.ones((5,5))
print(x * y[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [72]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [73]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 17) ( 0, 37) ( 1, 21) ( 1, 32) ( 5, 22) ( 5, 34) (16, 27) (16, 46)
 (17, 37) (21, 32) (22, 34) (26, 32) (26, 65) (27, 46) (32, 65) (34, 74)
 (34, 98) (36, 50) (36, 63) (46, 47) (46, 52) (46, 75) (46, 77) (47, 52)
 (50, 63) (56, 58) (56, 92) (58, 92) (74, 98) (75, 77)]


In [74]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [75]:
def moving_average(a, i=3) :
    ret = np.cumsum(a, dtype=float)
    ret[i:] = ret[i:] - ret[:-i]
    return ret[i - 1:] / i
x = np.arange(20)
print(moving_average(x, i=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [76]:
from numpy.lib import stride_tricks
def rolling(x, window):
    shape = (x.size - window + 1, window)
    strides = (x.strides[0], x.strides[0])
    return stride_tricks.as_strided(x, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [77]:
x = np.random.randint(0,2,100)
np.logical_not(x, out=x)
x = np.random.uniform(-1.0,1.0,100)
np.negative(x, out=x)

array([ 0.25383454,  0.37915866,  0.98264039, -0.5684633 ,  0.30437981,
       -0.57244676,  0.2360423 , -0.97970943,  0.70406356,  0.11284512,
       -0.22765415, -0.70084643,  0.71714063,  0.20329457, -0.36915089,
        0.35018373, -0.62296196, -0.00165735, -0.63249122,  0.61894125,
        0.7846069 , -0.80257152,  0.45657984, -0.17532417, -0.54924465,
       -0.02656371, -0.72679175, -0.22583235,  0.6570984 , -0.11172431,
        0.2142568 ,  0.14153181, -0.10431838, -0.85004606, -0.50086965,
       -0.53122949,  0.69242595, -0.15543342, -0.54703458, -0.24265064,
       -0.99042922,  0.67365101, -0.37452103,  0.34326335,  0.72933198,
       -0.95387969, -0.25519328, -0.55647687, -0.92305266, -0.02866272,
        0.30518955, -0.8940784 , -0.98483164, -0.77908297, -0.99553495,
        0.60304741,  0.23299185, -0.62108381,  0.37988129, -0.89619594,
       -0.87761977,  0.17969176, -0.30183711,  0.7425856 , -0.86152572,
       -0.72054326,  0.77688784, -0.63289742,  0.37119496, -0.31

In [78]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[6.13728231 4.81011059 5.4145135  3.23464999 4.40979205 3.09144639
 4.11421693 5.38212009 0.07841589 5.07325725]


In [79]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 4.81289177  0.8621628   2.20503863  3.15495777  2.31776115  0.47278758
   0.09899124  0.99457057  3.85684826  2.5545586 ]
 [ 5.43100717  4.27853517  2.20383777  0.30395928  5.92012549  3.68263086
   4.48221862  4.95366773  4.31942038  6.59335255]
 [15.43689283  2.08399237  2.77246276  7.98648097  0.11778953 10.64854487
   3.31965033  0.52436805  5.71955826 10.7122956 ]
 [ 2.73128253  9.24925659  1.4879621   5.77142473 10.42514823  2.15996478
   5.1738775   8.32296975 12.44631739  3.01527114]
 [ 1.01608763 13.55835851  7.78511757  9.16843652 15.04486339  2.97402764
  11.28950899 13.56347922 12.26019556  9.08555147]
 [ 4.09200485  1.78281328  1.71527322  2.19791709  3.21642186  0.30820058
   0.72334753  1.82730443  4.71150352  2.71701553]
 [ 0.24800348  5.21814223  1.18621517  1.72414466  6.43561894  2.22027754
   2.01772098  4.49917771  9.25789129  1.60160651]
 [ 4.18565896 10.05011501  1.26300118  6.77988963 11.13965594  3.26291318
   5.19790401  8.82905643 13.87027476  2.29344169]


In [80]:
#problem 80